@host=https://localhost:7295
@jwtToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjZTI5Y2IxNi01YTI2LTQ3NmMtYTI5ZC01M2E4NTA4Zjk2ODciLCJnaXZlbl9uYW1lIjoiSmFrZSIsImZhbWlseV9uYW1lIjoiVG9sbGV0dGUiLCJlbWFpbCI6Impha2V0b2xsZXR0ZUBnbWFpbC5jb20iLCJqdGkiOiJhYjVjZWZiMC05MGMzLTQwNWUtYmJiNy0xODFhNWIxMDZhNTciLCJleHAiOjE3MzI5MjM0NTcsImlzcyI6IkJ1YmVyRGlubmVyIiwiYXVkIjoiQnViZXJEaW5uZXIifQ.uF8SwWguIN_Jjq8EYOnsxpdnPtQDzoWQAc6K0Oqey-s
@hostId=12d27a03-6e88-43da-b990-ae6397a0c5fd
POST {{host}}/hosts/{{hostId}}/menus
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "name": "Yummy Menu",
  "description": "A delicious menu",
  "sections": [
    {
      "name": "Appetizers",
      "description": "Start your meal off right",
      "items": [
        {
          "name": "Cheese Sticks",
          "description": "Fried cheese sticks"
        }
      ]
    }
  ]
}
###