@host=https://localhost:7295
@jwtToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyMjYzYjU5Yi02Yzc2LTQ3ZTYtYWM1OC02NjhjOTQ0NDhlZTciLCJnaXZlbl9uYW1lIjoiSmFrZSIsImZhbWlseV9uYW1lIjoiVG9sbGV0dGUiLCJlbWFpbCI6Impha2V0b2xsZXR0ZUBnbWFpbC5jb20iLCJqdGkiOiJhOTNjMmQ3Yi1kYjk3LTQ0OWQtOTViNy0zYTJhOTQxZGQ5YTQiLCJleHAiOjE3MzI4MTU5MzYsImlzcyI6IkJ1YmVyRGlubmVyIiwiYXVkIjoiQnViZXJEaW5uZXIifQ.5HcjD1vNRpDO9MqQt0fBi8SgJO5006nze8jrylOCYCU
GET {{host}}/dinners
Authorization: Bearer {{jwtToken}}
###