@host=https://localhost:7295
@jwtToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3OWI2MDdmMi1lZTdhLTQ1NjYtYjA0MC05NDFhOGVmZWU1OGQiLCJnaXZlbl9uYW1lIjoiSmFrZSIsImZhbWlseV9uYW1lIjoiVG9sbGV0dGUiLCJlbWFpbCI6Impha2V0b2xsZXR0ZUBnbWFpbC5jb20iLCJqdGkiOiIxMWZkMmYwZS1lOTk5LTQ2OGYtYTUzZi1iZmU2MTI5MmJhODIiLCJleHAiOjE3MzI4OTkwMzIsImlzcyI6IkJ1YmVyRGlubmVyIiwiYXVkIjoiQnViZXJEaW5uZXIifQ.RW8gdia0-yBFoRtFq6C4pe_dedbWCTrm0Al_lA_VEPk
GET {{host}}/dinners
Authorization: Bearer {{jwtToken}}
###